float:
  angular:
    - base_args: ["@metric", "@dimension"]
      constructor: MilvusFLAT
      disabled: false
      docker_tag: ann-benchmarks-milvus
      module: ann_benchmarks.algorithms.milvus
      name: milvus-flat
      run_groups:
        FLAT:
          args:
            placeholder: [0]
    - base_args: ["@metric", "@dimension"]
      constructor: MilvusIVFFLAT
      disabled: false
      docker_tag: ann-benchmarks-milvus
      module: ann_benchmarks.algorithms.milvus
      name: milvus-ivfflat
      run_groups:
        IVFFLAT:
          args:
            nlist: [1024, 2048, 4096, 8192]
          query_args: [[50, 100, 200]]
    - base_args: ["@metric", "@dimension"]
      constructor: MilvusIVFSQ8
      disabled: false
      docker_tag: ann-benchmarks-milvus
      module: ann_benchmarks.algorithms.milvus
      name: milvus-ivfsq8
      run_groups:
        IVFSQ8:
          args:
            nlist: [1024, 2048, 4096, 8192]
          query_args: [[50, 100, 200]]
    - base_args: ["@metric", "@dimension"]
      constructor: MilvusIVFPQ
      disabled: false
      docker_tag: ann-benchmarks-milvus
      module: ann_benchmarks.algorithms.milvus
      name: milvus-ivfpq
      run_groups:
        IVFPQ:
          args:
            nlist: [1024, 2048, 4096, 8192]
            m: [2, 4]
          query_args: [[50, 100, 200]]
    - base_args: ["@metric", "@dimension"]
      constructor: MilvusHNSW
      disabled: false
      docker_tag: ann-benchmarks-milvus
      module: ann_benchmarks.algorithms.milvus
      name: milvus-hnsw
      run_groups:
        HNSW:
          args:
            M: [8, 12, 16, 24, 36, 48]
            efConstruction: [200, 500]
          query_args: [[40, 80, 120, 200, 400]]
    - base_args: ["@metric", "@dimension"]
      constructor: MilvusSCANN
      disabled: false
      docker_tag: ann-benchmarks-milvus
      module: ann_benchmarks.algorithms.milvus
      name: milvus-scann
      run_groups:
        SCANN:
          args:
            nlist: [1024, 2048, 4096, 8192]
          query_args: [[50, 100, 200]]
  euclidean:
    - base_args: [ "@metric", "@dimension" ]
      constructor: MilvusFLAT
      disabled: false
      docker_tag: ann-benchmarks-milvus
      module: ann_benchmarks.algorithms.milvus
      name: milvus-flat
      run_groups:
        FLAT:
          args:
            placeholder: [ 0 ]
    - base_args: [ "@metric", "@dimension" ]
      constructor: MilvusIVFFLAT
      disabled: false
      docker_tag: ann-benchmarks-milvus
      module: ann_benchmarks.algorithms.milvus
      name: milvus-ivfflat
      run_groups:
        IVFFLAT:
          args:
            nlist: [512, 1024, 2048, 4096, 8192 ]
          query_args: [ [ 5, 10, 50, 100 ] ]
    - base_args: [ "@metric", "@dimension" ]
      constructor: MilvusIVFSQ8
      disabled: false
      docker_tag: ann-benchmarks-milvus
      module: ann_benchmarks.algorithms.milvus
      name: milvus-ivfsq8
      run_groups:
        IVFSQ8:
          args:
            nlist: [ 512, 1024, 2048, 4096, 8192 ]
          query_args: [ [ 5, 10, 50, 100 ] ]
    - base_args: [ "@metric", "@dimension" ]
      constructor: MilvusIVFPQ
      disabled: false
      docker_tag: ann-benchmarks-milvus
      module: ann_benchmarks.algorithms.milvus
      name: milvus-ivfpq
      run_groups:
        IVFPQ:
          args:
            nlist: [ 256, 512, 1024, 2048, 4096 ]
            m: [ 4, 8, 16, 32]
          query_args: [ [10, 50, 100 ] ]
    - base_args: [ "@metric", "@dimension" ]
      constructor: MilvusHNSW
      disabled: false
      docker_tag: ann-benchmarks-milvus
      module: ann_benchmarks.algorithms.milvus
      name: milvus-hnsw
      run_groups:
        HNSW:
          args:
            M: [ 8, 12, 16, 24, 36, 48]
            efConstruction: [200, 500 ]
          query_args: [ [ 20, 40, 80, 120, 200, 400 ] ]
    - base_args: [ "@metric", "@dimension" ]
      constructor: MilvusSCANN
      disabled: false
      docker_tag: ann-benchmarks-milvus
      module: ann_benchmarks.algorithms.milvus
      name: milvus-scann
      run_groups:
        SCANN:
          args:
            nlist: [512, 1024, 2048, 4096, 8192 ]
          query_args: [ [ 5, 10, 50, 100  ] ]
