float:
  any:
  - base_args: ['@metric']
    constructor: PGVectorIVFFLAT
    disabled: false
    docker_tag: ann-benchmarks-pgvector
    module: ann_benchmarks.algorithms.pgvector
    name: pgvector-ivfflat
    run_groups:
      IVFFLAT:
        args:
          nlist: [ 128, 256, 512, 1024, 2048, 4096 ]
        query_args: [ [ 1, 10, 20, 50, 100 ] ]
  - base_args: [ '@metric' ]
    constructor: PGVectorHNSW
    disabled: false
    docker_tag: ann-benchmarks-pgvector
    module: ann_benchmarks.algorithms.pgvector
    name: pgvector-hnsw
    run_groups:
      M-16:
        arg_groups: [ { M: 16, efConstruction: 200 } ]
        args: { }
        query_args: [ [ 10, 20, 40, 80, 120, 200, 400, 800 ] ]
      M-24:
        arg_groups: [ { M: 24, efConstruction: 200 } ]
        args: { }
        query_args: [ [ 10, 20, 40, 80, 120, 200, 400, 800 ] ]
