float:
  angular:
  - base_args: ['@metric']
    constructor: Redisearch
    disabled: false
    docker_tag: ann-benchmarks-redisearch
    module: ann_benchmarks.algorithms.redisearch
    name: redisearch-hnsw
    run_groups:
      redisearch:
        arg_groups: [[1, 2, 4, 8, 12, 16, 24, 36, 48], [200, 500]]
        args: {}
        query_args: [[10, 20, 40, 80, 120, 200, 400]]
  euclidean:
    - base_args: [ '@metric' ]
      constructor: Redisearch
      disabled: false
      docker_tag: ann-benchmarks-redisearch
      module: ann_benchmarks.algorithms.redisearch
      name: redisearch-hnsw
      run_groups:
        redisearch:
          arg_groups: [[1, 2, 4, 8, 12, 16, 24, 36, 48], [200, 500]]
          args: {}
          query_args: [[20, 40, 80, 120, 200, 400]]
