float:
  angular:
  - base_args: ['@metric']
    constructor: Qdrant
    disabled: false
    docker_tag: ann-benchmarks-qdrant
    module: ann_benchmarks.algorithms.qdrant
    name: qdrant-hnsw
    run_groups:
      default:
        args: [
          ['none', 'scalar', 'binary'], #quantization
          [8, 12, 16, 24, 36, 48], #m
          [ 200, 500 ], #ef_construct
        ]
        query_args: [
          [null, 40, 80, 120, 200, 400], #hnsw_ef
          [True, False], # re-score
        ]
    euclidean:
      - base_args: [ '@metric' ]
        constructor: Qdrant
        disabled: false
        docker_tag: ann-benchmarks-qdrant
        module: ann_benchmarks.algorithms.qdrant
        name: qdrant-hnsw
        run_groups:
          default:
            args: [
              [ 'none', 'scalar', 'binary' ], #quantization
              [8, 12, 16, 24, 36, 48], #m
              [ 200, 500 ], #ef_construct
            ]
            query_args: [
              [ null, 20, 40, 80, 120, 200, 400 ], #hnsw_ef
              [ True, False ], # re-score
            ]
