float:
  angular:
  - base_args: ['@metric']
    constructor: Weaviate
    disabled: false
    docker_tag: ann-benchmarks-weaviate
    module: ann_benchmarks.algorithms.weaviate
    name: weaviate
    run_groups:
      weaviate:
        args: [[ 8, 12, 16, 24, 36, 48], [200, 500]]
        query_args: [[40, 80, 120, 200, 400]]
  euclidean:
    - base_args: [ '@metric' ]
      constructor: Weaviate
      disabled: false
      docker_tag: ann-benchmarks-weaviate
      module: ann_benchmarks.algorithms.weaviate
      name: weaviate
      run_groups:
        weaviate:
          args: [[ 8, 12, 16, 24, 36, 48 ], [ 200, 500 ]]
          query_args: [ [ 20, 40, 80, 120, 200, 400 ] ]
